### ISSUE TITLE
执行 go run 没法加载依赖包

### ISSUE THREAD

**Issue by suyar** [wangle201210/autoAddCommit#1]
![image](https://user-images.githubusercontent.com/15704489/129993933-8cd5c8f0-6390-4e1f-9beb-c0c6edd4f7e3.png)

**Comment by wangle201210** [comment]
你 添加下环境变量 GOPROXY=https://goproxy.io,direct

**Comment by suyar** [comment]
> 你 添加下环境变量 GOPROXY=https://goproxy.io,direct

可以了非常感谢
